### ISSUE TITLE
Drowning casues a bug

### ISSUE THREAD

**Issue by Raptorq1** [Techokami/SonicWorldsNext#108]
when the drown timer is at 0 and you jump on a teleporter exactly when you drown all collision breaks

**Comment by DimensionWarped** [comment]
>exactly when you drown

So are you saying this doesn't occur unless you do a frame perfect jump onto the teleporter or is there a window of time?

**Comment by Raptorq1** [comment]
I meant before you drown

**Comment by Raptorq1** [comment]
![Screenshot_20231117-101837](https://github.com/Techokami/SonicWorldsNext/assets/106418027/58a7b054-fd39-4dd0-922c-5a983daadbbd)
it happens at this teleporter oh and there is a window of time

**Comment by NeonSRB2** [comment]
This does produce some very strange behavior... but at the very least the drown timer can be reset for the teleport.

**Comment by NeonSRB2** [comment]
Fixed in pull request

**Comment by Raptorq1** [comment]
@NeonSRB2 what do you mean fixed the bug is still there

**Comment by PetscopF** [comment]
> @NeonSRB2 what do you mean fixed the bug is still there

You likely did not sync your repository with the base engine repository. If you cloned the repository, then it will not synchronize. I'd suggest making a workflow with [this action in a workflow if you host your repository on GitHub.](https://github.com/marketplace/actions/actions-template-sync)
