### ISSUE TITLE
Text is weirdly sized

### ISSUE THREAD

**Issue by hardcaz** [Techokami/SonicWorldsNext#129]
Text seems to be too big

**Comment by hardcaz** [comment]
Not a angle specific issue (happens in 4.2.1) (unsure if the text wasn't weird on 4.2)

**Comment by EnterTheVoid-x86** [comment]
Same issue here

**Comment by Raptorq1** [comment]
What device where you using to run the engine pc or android

**Comment by DimensionWarped** [comment]
Can you each please post pictures of your issues and give specific descriptions of what platforms, engine versions, and Godot versions that you are using?

**Comment by hardcaz** [comment]
> What device where you using to run the engine pc or android

PC

**Comment by DimensionWarped** [comment]
And are you planning to provide the other three quarters of what I asked?

**Comment by Raptorq1** [comment]
Yea dimension warped said to provide pictures of the issue 

Like this 
![Screenshot_20240120-220553](https://github.com/Techokami/SonicWorldsNext/assets/106418027/74a6a6c7-8e71-40ba-9741-0df9a33adcfb)
![Screenshot_20240120-220606](https://github.com/Techokami/SonicWorldsNext/assets/106418027/2cefd8fe-cd74-4085-8485-727d55334838)
![Screenshot_20240120-220644](https://github.com/Techokami/SonicWorldsNext/assets/106418027/b5322022-d61d-4858-b463-d33c4a4698e0)

**Comment by EnterTheVoid-x86** [comment]
Sorry for the late response, I can't show images right now but the ones above are what we see on PC too. We are using Godot 4 on latest commit, Multi-platform

**Comment by EnterTheVoid-x86** [comment]
The issue does not happen on the Godot 3 branch.

**Comment by hardcaz** [comment]
> Yea dimension warped said to provide pictures of the issue
> 
> Like this ![Screenshot_20240120-220553](https://private-user-images.githubusercontent.com/106418027/298491399-74a6a6c7-8e71-40ba-9741-0df9a33adcfb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjE0NTQsIm5iZiI6MTcwNjAyMTE1NCwicGF0aCI6Ii8xMDY0MTgwMjcvMjk4NDkxMzk5LTc0YTZhNmM3LThlNzEtNDBiYS05NzQxLTBkZjlhMzNhZGNmYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNDQ1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2M0N2ZiM2Q4OGE2ZjZkOTcyZTgwY2RiYWQwYjgwNzg3MjdhZDJmODcwMGM0OGI4YjhiZDMzODZjMGU5YzRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lXTPB4ze4bkSYpAc3EHI_KWXM5RWykicnZrZLIA7vZc) ![Screenshot_20240120-220606](https://private-user-images.githubusercontent.com/106418027/298491402-2cefd8fe-cd74-4085-8485-727d55334838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjE0NTQsIm5iZiI6MTcwNjAyMTE1NCwicGF0aCI6Ii8xMDY0MTgwMjcvMjk4NDkxNDAyLTJjZWZkOGZlLWNkNzQtNDA4NS04NDg1LTcyN2Q1NTMzNDgzOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNDQ1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NDE0ZTJlZTc3NTJjNGU3NDcxYWYzMGE5YzZkODc0YzcyNGQyODM1NjU5ZjU3Y2JhZGVhOTIxYWRiZDk4NzA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xuQeWr_AGyuYHeWSvlhOoNDjYwsMO13vO-p1yw3zhJE) ![Screenshot_20240120-220644](https://private-user-images.githubusercontent.com/106418027/298491406-b5322022-d61d-4858-b463-d33c4a4698e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjE0NTQsIm5iZiI6MTcwNjAyMTE1NCwicGF0aCI6Ii8xMDY0MTgwMjcvMjk4NDkxNDA2LWI1MzIyMDIyLWQ2MWQtNDg1OC1iNDYzLWQzM2M0YTQ2OThlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyM1QxNDQ1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDhlYzNmMmU4YWZmMGMxMDcwNDE0OGFmYTY5MzgzZDA4ZGRhYzcxZTgyNDQ2MzMzOWExMzNmYzJlZDhlNmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9XuRjWW98Cdp-q3f_eC0xb4WzllqzN3xDuaVZcNJ2RM)

Those android screenshots of the gameplay have the same text sizing issues i have on my computer

**Comment by Renhoex** [comment]
This is the first time I've seen this issue, this is really weird since I've never encountered or been able to replicate this issue myself, even harder now as the current version uses godot's label system.
This also explains why godot 3's system works because I coded that one myself.
my only guess is that it could be the font scaling mode?

Select the font file from the editor (see image), go to the import settings and try setting scaling mode to disabled, click re-import and tell us if that makes a difference.
![image](https://github.com/Techokami/SonicWorldsNext/assets/26295900/1833217b-9258-43d8-9a6e-64bc12f50256)

**Comment by Raptorq1** [comment]
It worked

**Comment by hardcaz** [comment]
It worked

**Comment by hardcaz** [comment]
Closed since work around exists

**Comment by NeonSRB2** [comment]
I did'nt read this issue before making my pull request but, really it's still an issue that the main repository still has this bug, so I'm not sure why they decided to close it?
