### ISSUE TITLE
Boss Template errors on call to BossBase.gd:_on_HitBox_area_exited(area) under certain conditions

### ISSUE THREAD

**Issue by DimensionWarped** [Techokami/SonicWorldsNext#15]
I first noticed this bug while playing at a higher resolution and then decided to try to reproduce it in the unmodified engine.

The specific error is:
`Invalid get index 'parent' (on base: 'Area2D').`
Stack Frames:
0 - res://Scripts/Boss/BossBase.gd:80 - at function: _on_HitBox_area_exited

I believe it is related to the position of the boss... the reason I encountered this more frequently in the higher resolution mode was because the boss was visible as it was descending and easy to hit as it was entering the frame. The easiest way I find to reproduce this error is to have the lightning shield and to hit the boss as it is coming down from the sky. The higher the more reliable.

Once the bug is first triggered it seems to persist throughout the fight and even as the boss is leaving. Simply entering his 'area' at that point makes triggering the error almost inevitable.

EDIT: Worth noting, it is accompanied by this error being logged, but not stopping the engine.

```
E 0:17:06.363   area_set_shape_disabled: Can't change this state while flushing queries. Use call_deferred() or set_deferred() to change monitoring state instead.
  <C++ Error>   Condition "area->get_space() && flushing_queries" is true.
  <C++ Source>  servers/physics_2d/physics_2d_server_sw.cpp:362 @ area_set_shape_disabled()
  <Stack Trace> BossBoundrySetter.gd:29 @ _on_BoundrySetter_body_entered()
```

The bug also intermittently happens without using the lightning shield to attack it out of frame.

**Comment by Renhoex** [comment]
Turns out there wasn't a check to see if the parent actually existed, I'm not entirely sure why it only worked when the boss was off screen but adding a check to make sure the object has a parent before removing it from the array fixed it and is now on the main branch.
