### ISSUE TITLE
Weird Collisions

### ISSUE THREAD

**Issue by shifturret** [Techokami/SonicWorldsNext#154]
trying to make a test level, collisions are not where they should be. Maybe I'm missing something as I'm new to Godot. any help appreciated.
![image_2024-05-18_172633676](https://github.com/Techokami/SonicWorldsNext/assets/158862239/675f96d8-04a4-4567-8f86-add2de08145f)

**Comment by shifturret** [comment]
posted in the wrong place

**Comment by NeonSRB2** [comment]
Try loading `res://Tileset/Worlds/WorldsTileMap.tres` instead of making your own tileset.
Sure, the tiles will be green instead of blue, but this seems temporary anyway for your purposes, and seemingly you can just swap the images around safely.
