### ISSUE TITLE
Add fluid rotation to the Player 

### ISSUE THREAD

**Issue by GiulianoA23** [Techokami/SonicWorldsNext#162]
My idea would be to add smooth rotation to the Player) something like RSDK or Sonic Mania **(or fangames like Sonic 3 AIR)**

**Comment by NeonSRB2** [comment]
Remember these in TailsAnimator.gd!
Unless you don't have tails in your game, his tails would'nt rotate smooth during a jump.
![image](https://github.com/Techokami/SonicWorldsNext/assets/118679101/2de04c27-0bbd-42ee-9125-1ba9ee80e0da)

**Comment by Caverns4** [comment]
In the last commit, I rewrote the comments about smooth rotation to make it easier to understand, so this should be redundant. Closing this issue now.
