### ISSUE TITLE
Rings animate while paused

### ISSUE THREAD

**Issue by NeonSRB2** [Techokami/SonicWorldsNext#169]
simply said, this shouldn't be happening

https://github.com/Techokami/SonicWorldsNext/assets/118679101/b3e37449-4837-43a1-bd1a-c20f3389f30f

Though this is recording off of a seperate branch, I didn't touch rings or pausing at all after I realized I was perfectly synched with the main branch.

**Comment by Caverns4** [comment]
This have been merged in, so there's no need to keep this open. Closing this issue :)
