### ISSUE TITLE
TextDisplay.gd - Middle Aligned Text is off-center

### ISSUE THREAD

**Issue by DimensionWarped** [Techokami/SonicWorldsNext#18]
Visible in the character select screen, the text is moderately right of where it should be. This becomes more apparent with a larger number of characters in the label.

![image](https://user-images.githubusercontent.com/7477617/218247510-e407dbd6-5e66-4844-b242-e2a7307dcd43.png)

In this screenshot where I'm working on a simple level select feature, the up and down arrows are at the center point of the screen. The S in Sonic is three vertical bars in the background left of center while S in Tails is 4 vertical bars to the right. Both text objects are supposed to be at horizontal position zero (dead center)

**Comment by NeonSRB2** [comment]
Since the switch to textLabels, this has been fixed, though a new issue with scaling on this screen is a thing now.
![image](https://github.com/Techokami/SonicWorldsNext/assets/118679101/b161d6ec-bc47-4f21-b1c5-17c63952395c)

**Comment by NeonSRB2** [comment]
Said issue is fixed with another project settings option, you can close this now

**Comment by NeonSRB2** [comment]
That project settings option was added to the pull request, so this issue really should be closed now

**Comment by Techokami** [comment]
Okay, okay, sheesh!
