### ISSUE TITLE
When special stages are complete it  doesn't show player

### ISSUE THREAD

**Issue by Raptorq1** [Techokami/SonicWorldsNext#181]
When you enter a special stage and complete it and it takes you back it doesn't show the player

**Comment by Renhoex** [comment]
What version of the framework were you using and what version of godot are you using?

Could you provide the location and anything that you did that could be related too if this happened in base zone?

**Comment by Raptorq1** [comment]
I'm using v2.9.0 and the version of godot that I'm using is 4.3

Uploading 2024-08-27-11-26-50-trim-00-38-0.MP4…

**Comment by Caverns4** [comment]
In SpecialStageRing.gd there is a check for player.character == player.CHARACTERS.SONIC
This is an oversight, it should be player.character == Global.CHARACTERS.SONIC
I will make this fix shortly.
