### ISSUE TITLE
Player super palettes don't look right and level ending screen from the hud says time instead of score 

### ISSUE THREAD

**Issue by Raptorq1** [Techokami/SonicWorldsNext#183]
Player super palettes don't look right and level ending screen from the hud says time instead of score 
![Screenshot_20240827-155041](https://github.com/user-attachments/assets/fe7e90ca-b1cd-4703-8add-1d91bef5e708)
![Screenshot_20240827-155205](https://github.com/user-attachments/assets/02e5637b-a069-418f-a4a4-ab6af8948c99)

**Comment by Caverns4** [comment]
On the first point, please make sure both your Sonic and Super Sonic sprites sheets are up to date, AS WELL as SuperSonicPal.png. This does not happen in the current up to date Worlds Next.
I am investigating the second issue currently.
