### ISSUE TITLE
The main tscin doesn't work

### ISSUE THREAD

**Issue by Sander-debuh** [Techokami/SonicWorldsNext#188]
The fucking uhhh everytime i try to ue the engine the fucking file said "its not there or open" or something so i wanna know how to fix it

**Comment by Caverns4** [comment]
Could you please be more specific? What you've said gives me nothing to work with. If I open Worlds Next on my end it works perfectly.
What version of Godot are you using, and is the version of World Next you've downloaded the currently up to date one?

**Comment by Raptorq1** [comment]
> The fucking uhhh everytime i try to ue the engine the fucking file said "its not there or open" or something so i wanna know how to fix it

Did you move the files to a new folder or are they still in the same folder because if you did move the files to a new folder that could be the issue

**Comment by PetscopF** [comment]
> The fucking uhhh everytime i try to ue the engine the fucking file said "its not there or open" or something so i wanna know how to fix it

As Raptor stated, it could possibly not be there. First check where the Project Settings states that the file is just in case (I believe it should be in the root scenes folder), then check (either in your file manager or even the FileSystem in Godot) and, if it doesn't seem to be there at all, then just copy the entire file from the original Worlds Next repository. These kinds of files - compared to .scn files - are text-based, so they can be easily read from any text editor. As such, you can make a new file by the same name in the same location, and copy from the [actual original file itself.](../blob/main/Scene/Main.tscn)

**Comment by Caverns4** [comment]
This is not an issue present or reproducible in base Sonic Worlds Next, so it doesn't belong here.
Make sure you are using Godot 4.2 or later and the Sonic Worlds Next version from this repository. If you downloaded the 3x version of Worlds Next, we don't support that any longer.
The Issues category is only for issues that are present or exist in the base framework, not external additions.
