### ISSUE TITLE
Weird Interaction with slopes

### ISSUE THREAD

**Issue by EmmaIsCompletelyAddictedToHomemadeBread** [Techokami/SonicWorldsNext#193]
![image](https://github.com/user-attachments/assets/323609ea-6aad-4f7d-a838-8067b45164a6)

When sonic is standing on a 1x2tile slope he starts walking down the slope very slowly. i tested in Sonic Mania to see how this would work out in a regular sonic game and i noticed in Mania, Sonic stands still if you stop while facing the direction of the top of the slope. he does the walking down the slope very slowly thing if you stop while facing the direction of the bottom of the slope. 

![image](https://github.com/user-attachments/assets/5cff60f7-c179-47ec-85d6-3c07a2210561) 
![image](https://github.com/user-attachments/assets/5edcf567-6306-44f8-90af-11713664395e)

**Comment by Caverns4** [comment]
You're right the behavior in Worlds Next matches Sonic 3's implementation - Sonic 3 is the only game that still applies angle detection when ground speed is 0.

In normal.gd at line 221, there is a comment that says "Apply slope factor" and then "ignore this if not moving for sonic 1 style slopes" - This is actually inaccurate. It's Sonic 1, 2, and Mania that do that, not just Sonic 1. Sonic 3 is the only outlier.

To fix this, you should need to simply put the "parent.movement.x +=" inside and if block that checks the player's movement x == 0. Should be fixing this soon, just want to make sure Sharb is onboard with it.

**Comment by Caverns4** [comment]
The fix for this issue is pending and awaiting approval, it should be merged in soon.
