### ISSUE TITLE
[Godot 4] `.godot` directory does not need to be included in the repository.

### ISSUE THREAD

**Issue by Sslaxx** [Techokami/SonicWorldsNext#41]
Related to #5 - relevant in particular to the Godot 4 branches.

The `.godot` directory is auto-generated by Godot 4 if it does not exist. Its purpose is the same as the `.import` directory in Godot 3, so can be included in `.gitignore`.

https://github.com/github/gitignore/blob/main/Godot.gitignore is a good example of a `.gitignore` which takes the `.godot` directory into account.

**Comment by BlueStaggo** [comment]
I tried to fix this myself, but it appears that the .godot directory is still there.

**Comment by Renhoex** [comment]
I see where it went wrong it was looking for a "source" directory that doesn't exist anymore, I tried changing it that should be fixing the issue so that auto generated files shouldn't be included in updates anymore

**Comment by Sslaxx** [comment]
You just need the `.godot` directory in there.

**Comment by Renhoex** [comment]
I've gone ahead and done that now.

**Comment by FriskTheFallenHuman** [comment]
This issue has been resolved on last night's Commit 👍
