### ISSUE TITLE
`.import` directory is present.

### ISSUE THREAD

**Issue by Sslaxx** [Techokami/SonicWorldsNext#5]
The `.import` directory is present both in the repository root directory and the `Source` directory. It isn't necessary to include this directory in the repository, and a `.gitignore` file could be useful to avoid including it (or other files) that are not required for the project to work.

https://github.com/Sslaxx/Godot_Sonic_Engine/blob/master/.gitignore is an example.

**Comment by Techokami** [comment]
Good call! I've cleaned up the repo with a quick gitignore file.
