### ISSUE TITLE
There is weird glitch one when it comes to Special Ring with Invincibility and Super mode

### ISSUE THREAD

**Issue by RepeatedKibbles** [Techokami/SonicWorldsNext#51]
After Special Stage, they stay with Invincibility/Super mode (Super mode changes back to normal sprite only left with Super pallet and still as fast as Super) (Invincibility mode more kind of like Super mode except normal. When it comes to shields, you can't use it as an ability rather end up using drop dash instead) leaving those who can still lose rings (like getting hit) after Special Stage
https://youtu.be/hIQWp7POpQw

**Comment by Renhoex** [comment]
Thanks for the report!
I went in and fixed the issues, invincibility and super forms get deactivated when you enter a special ring now.

I also fixed that bug where the ai will spam the spindash button if it gets stuck.
