### ISSUE TITLE
Colliding rings when hurt don't collect them

### ISSUE THREAD

**Issue by Kekun** [Techokami/SonicWorldsNext#60]
I have been hurt by a motobug and fell on rings, while falling hurt the rings weren't collected, which feels odd to me, I may be misremembering but I think in the classics they would have been collected.

**Comment by Renhoex** [comment]
When sonic gets hit he can't collect rings for about a second, this is intentional and how it works in the original game.

**Comment by Kekun** [comment]
Just to be clear, I'm not talking about the lost, moving rings but rings floating normally, is that the case for these too?

**Comment by Renhoex** [comment]
yep, i tested it in sonic 3 by getting the rhino to hit me and here it is
![image](https://github.com/Techokami/SonicWorldsNext/assets/26295900/61cd6bea-d765-415c-90fb-a906a50dc234)

**Comment by Kekun** [comment]
OK, thanks, let's close the issue then. :)
