### ISSUE TITLE
I am trying to add super theme

### ISSUE THREAD

**Issue by Raptorq1** [Techokami/SonicWorldsNext#62]
I am trying to add a super theme for my game but the invcibilty theme keeps playing.

**Comment by Renhoex** [comment]
This one requires a bit of set up, it'll be one of the things we'll have a guide for later on when we get around to setting up some documentation.

If you want to add a super theme, go into the global script file. 
`res://Scripts/Global/Global.gd`

at line 46 you should see `var themes = [prel...` add your super theme file to the end of this array, should look something like this
`var themes = [preload("res://Audio/Soundtrack/1. SWD_Invincible.ogg"),preload("res://Audio/Soundtrack/2. SWD_SpeedUp.ogg"),preload("res://Audio/Soundtrack/4. SWD_StageClear.ogg"),preload("res://Audio/Soundtrack/YourSuperTheme.ogg")]`

Then you'll want to go into the super form start script `res://Scripts/Player/States/SuperStart.gd` at line 30 change `Global.currentTheme = 0`
to
`Global.currentTheme = 3`

This should play the third slot theme in the super music, let us know if there's any issues.

**Comment by Renhoex** [comment]
Ah that seems to be an oversight in the monitors.
go into the monitor script res://Scripts/Objects/Monitor.gd

replace all instances of 
`playerTouch.get("super")`
with
`playerTouch.get("isSuper")`

**Comment by DimensionWarped** [comment]
For future notice, all stuff like this should be put into discussions, not into issues since an issue implies there is something wrong with the stock code.
