### ISSUE TITLE
Frame drops cause game to skip actions.

### ISSUE THREAD

**Issue by SuperSonic472** [Techokami/SonicWorldsNext#68]
(Mostly) Self explanatory, frame dropping causes you to miss rings and not get hit by badniks. The fix is most likely delta timing.

**Comment by DimensionWarped** [comment]
Post a video please, even if it's just mobile phone footage.

**Comment by SuperSonic472** [comment]
I'm currently not able to reproduce it, if I find a way to force lag I'll send it.

**Comment by DimensionWarped** [comment]
Closing due to lack of ability to reproduce, no demonstration, and no response from the reporter.

Please open a new ticket with a demonstration if you want to pursue this in the future.
