### ISSUE TITLE
[Bug] While controller is plugged in, I can't crouch unless both the keyboard down and the controller down are held simultaneously.

### ISSUE THREAD

**Issue by DimensionWarped** [Techokami/SonicWorldsNext#8]
To elaborate further, I can sometimes roll with just one or the other if I very deliberately press down while going at high speed, but it seems button presses aren't persistent (IE if I'm holding down on the controller I never get more than a single frame where I'm actually considered to be holding down) which makes things rather awkward.

Test performed with a PS5 controller using Steam for compatibility plus Godot 3.5

**Comment by DimensionWarped** [comment]
Curiously, this has stopped happening after I remapped my controls once. I say curiously because after restarting the game my control configuration didn't stick, but the bug was no longer reproducible at that point anyway.

If this ends up being unreproducible, we can go ahead and close this ticket.

**Comment by Renhoex** [comment]
I believe at some point I screwed up the controller config code, this was fixed in a recent update but the control buttons maybe have been saved with the broken config which got fixed when you reset your controls.

I'll leave this thread open for further investigation for now

**Comment by Renhoex** [comment]
Forgot to mention but the pressing down to drop switch is used for the tails assist since tails basically just re uses the pole code and it was easier to just add the drop code to the pole then making an entire system for tails to just carry player 1, it's why I haven't caught many issues with it because I've only tested it with tails.

**Comment by DimensionWarped** [comment]
I don't think we are actively working on this and now that no one is actually experiencing this issue (which appeared to just be a mangled configuration anyway), I'm going to close it. We can reference it if something similar comes up in the future.
