### ISSUE TITLE
Hanging Bar mechanics (jump off, fall through)

### ISSUE THREAD

**Issue by DimensionWarped** [Techokami/SonicWorldsNext#9]
I have a little attachment to the hanging bar gimmick having created the original rendition of it in the old Sonic Worlds... and visiting the current implementation of it (and I'm not sure how much of it I did this right the first time around) and comparing it to the variant of it that appears in Sonic 2's wing fortress stage made me realize there's a couple discrepancies.

1. In Sonic 2 when you disembark from a hanging bar (via jump, the only way to get off it as far as I'm aware), you will still be in the animation for hanging until you hit the ground. Honestly, I could take this behavior or leave it. Going back into jump is fine and leaves players less vulnerable (and I find a lot of forced vulnerability while falling in Sonic games to be annoying).

2. The current implementation appears to have no way to allow the player to fall through the hanging bar. Sonic 2 has a rather awkward mechanic for deciding whether or not you'll fall through... if you jump while holding left or right off of a bar, the next time you would grab onto the bar you will always fall through it (regardless of whether you are holding left or right at the time). If you jump while not holding left or right, you will catch the bar. Personally, I think this should be swapped to a simple check for whether or not the player is holding down (regardless of previous interactions with the bar) when the player would catch it, they should fall through it. Easy to implement, hard to screw yourself over when you don't to.

I also personally think I allowed the player to accrue speed by holding in a direction while hanging onto the bar in the original (meaning the player could have a full velocity jump coming getting off the bar if they held in that direction for a while), but that mechanic is perhaps poorly communicated and largely unnecessary. That said, it would probably feel better if the horizontal speed coming off of the bar is at least slightly affected by whether you are holding left or right when you drop off instead of having to accelerate from 0. In the case of moving bars especially, ideally the current velocity of the bar would be applied to the player's speed at the time of jumping off.

I can submit a pull request to implement these if such improvements are desired.

**Comment by Renhoex** [comment]
Our implementation of the hanging bar is based on the one from sonic 3 not 2 as it's sharing the code for tails flight assist.

**Comment by DimensionWarped** [comment]
Presuming this is intended to behave the same as the sky sanctuary hanging bars, holding left/right should apply some immediate x velocity as I suggested and holding down while pressing jump should make the player disembark from the bar with very little (or perhaps no) downward y velocity.

Sonic 3K has no mechanic for falling through a bar deliberately, but I'm still rather keen on having you just not grab it if you hold down from the onset. Your call though.

**Comment by DimensionWarped** [comment]
Ah, just noticed there is this little variable for the hanging object:

export var holdDownToDrop = false

Turning that on is... not great. It's buggy. It kinda works but it messes up the general interactions with the object. It does show that some effort was made to support this intended behavior though.

**Comment by DimensionWarped** [comment]
Noticed a bug in the hanging bar at its default configuration:

The jumping off mechanic only responds to button 1 and not buttons 2/3. Normally all three action buttons are treated the same for purposes like this.

**Comment by Renhoex** [comment]
I'll have to go through the code to add support for other action buttons.

should mention, the pressing down to drop switch is used for the tails assist since tails basically just re uses the pole code and it was easier to just add the drop code to the pole then making an entire system for tails to just carry player 1, it's why I haven't caught many issues with it because I've only tested it with tails.

**Comment by DimensionWarped** [comment]
Hey, I'm going to go ahead and take care of the different button issues for this as well as all of my gimmicks in the CNZBarrel branch. I went ahead and added a couple functions to player that let you check for any action button pressed, held, or either. While I'm at it I'll take care of the fact that players can't willingly jump off of Tails carry and add a toggle to let players fall through without grabbing by holding down.

**Comment by DimensionWarped** [comment]
https://github.com/Techokami/SonicWorldsNext/pull/23

Closed on account of merging this pull request
