### ISSUE TITLE
When i change the super music it doesnt stop playing

### ISSUE THREAD

**Issue by Raptorq1** [Techokami/SonicWorldsNext#92]
All I did to make this issue happen is change the super track

here's the original code 

Global.currentTheme = 0
		Global.effectTheme.stream = Global.themes[Global.currentTheme]
		Global.effectTheme.play()
To this, this is a example
Global.currentTheme = 5
		Global.effectTheme.stream = Global.themes[Global.currentTheme]
		Global.effectTheme.play()
And when I let super sonic run out the music wouldn't stop

**Comment by DimensionWarped** [comment]
Issue doesn't impact the codebase without actual code changes. If this had simply been changing the value of the invincibility music in the Global.themes array, I would have been inclined to say we had an issue, but after validating that I can change that music myself without issue I'm no longer of that opinion.

Reminder that we only support the engine as it comes, not as you may have made it.

**Comment by NeonSRB2** [comment]
> All I did to make this issue happen is change the super track
> 
> here's the original code

Here's the line that causes the issue:
`if Global.currentTheme == 0 and Global.effectTheme.is_playing():`

You changed currentTheme in your code example to 5, so you should make it try to stop if that's playing as well.
Here's an example:
`if (Global.currentTheme == 0 or Global.currentTheme == 5) and Global.effectTheme.is_playing():`
